version: "3"

volumes:
    wp_db:
        driver: local
        driver_opts: 
            type: none
            o: bind
            device: ${HOME}/data/maria_db
    wp_web:
        driver_opts: 
            type: none
            o: bind
            device: ${HOME}/data/wordpress

networks:
    inception:
        driver: bridge

services:
    nginx:
        depends_on:
            - wordpress
        build: nginx
        ports:
            - 443:443
        restart: on-failure
        volumes:
            - wp_web:/var/www/mysite/
        extra_hosts: 
            - "wbritni.42.fr:127.0.0.1"
        networks:
            - inception

    wordpress:
        depends_on:
            - maria_db
        build: wordpress
        ports:
            - "9000"
        volumes:
            - wp_web:/var/www/mysite/
        restart: on-failure
        networks:
            - inception
    
    maria_db:
        build: maria_db
        ports:
            - "3306:3306"
        volumes:
            - wp_db:/var/lib/mysql
        environment: 
            MARIA_LGN: ${MARIA_LGN}
            MARIA_PWD: ${MARIA_PWD}
        restart: on-failure
        networks:
            - inception
        env_file: .env
